[project]
name = "live-api-evals-and-audio-session-auditing"
version = "0.1.0"
description = "FastAPI application for the info_gather_agent utilizing ADK Gemini Live API Toolkit"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk==2.0.0",
    "google-genai",
    "google-cloud-storage",
    "numpy>=2.5.1",
]
